[package]
name = "compost-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
actix-cors = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
compost = { path = "../compost" }